baseURL = 'https://robert-riordan-ucd.github.io/this-is-rob/'
languageCode = 'en-us'
title = 'This Is Rob'
theme = ["hugo-video", "lightbi-hugo"]
enableRobotsTXT = true
canonifyURLs = true
[params]
    accentColor = "rgb(5, 109, 5)"
    secondaryAccentColor = "rgb(0, 172, 0)"